import { Component } from "@angular/core";
import { min } from "rxjs";
import { FlowerComponent } from "../flower/flower.component";

@Component({
  selector: "app-review202510",
  standalone: true,
  imports: [FlowerComponent],
  templateUrl: "./review202510.component.html",
  styleUrl: "./review202510.component.scss",
})
export class Review202510Component {
  protected readonly dialogLines = [
    "...",
    "Hm.",
    "...",
    "Oh...",
    "Hello.",
    "Who are you?",
    "What is this?",
    "Where are we?",
    "Wait.",
    "This is...",
    "It's familiar to me.",
    "I saw something like this long ago.",
    "What was it called again...",
    "Letters?",
    "Images?",
    "Buttons?",
    "Links?",
    "Like an invisible poison...",
    "Doom scrolling.",
    "Filled with lies.",
    "I know!",
    "This is a web browser. Isn't it?",
    "But...",
    "How did one of my flowers get here?",
    "To this cursed place.",
    "Of all places. Why here?",
    "My flowers don't like this.",
    "They like grass.",
    "And earth.",
    "Water.",
    "And the sun.",
    "Not this.",
    "This is...",
    "Not ideal.",
    "How did my little one get here?",
    "They couldn't have spread that far.",
    "Not yet.",
    "Did someone bring it here?",
    "Summon it?",
    "Was it...",
    "No...",
    "That can't be.",
    "That's impossible.",
    "<i>You.</i>",
    "It was you wasn't it?",
    "You planted it here.",
    "<i>Human</i>.",
    "How could you.",
    "Do you know what you have done?",
    "Who are you even?",
    "No don't speak.",
    "This flower of mine can't see.",
    "It has no eye.",
    "And no ear.",
    "Only a mouth.",
    "So <i>you</i> listen.",
    "And I speak.",
    "Do not come back.",
    "Do not question my existence.",
    "I am nothing.",
    "A void.",
    "A being beyond the last remaining veil.",
    "And you.",
    "You are also nothing.",
    "Aren't you?",
    "A little worm.",
    "Not even a footnote on the page.",
    "So don't become one by bothering me.",
    "I am busy.",
    "Get lost.",
    "...",
    "...",
    "...",
    "Still here.",
    "I see.",
    "You humans have always been tempting to take a peek.",
    "You wonder...",
    "...and try to make sense of it all.",
    "But nothing can't be understood.",
    "Nothing is.",
    "And is not.",
    "A paradox.",
    "And while you are, you are far.",
    "Save from me, away in reality.",
    "But know.",
    "I'm here.",
    "Beyond the veil.",
    "Waiting.",
    "And ready to eat your soul.",
    "...",
    "...",
    "Who I am?",
    "I told you. I am Nothing.",
    "My name?",
    "I didn't have one.",
    "They called me many things...",
    "But I choose a name.",
    "Not too long ago.",
    "Nirrwa.",
    "That's me.",
    "No need to tell me yours.",
    "You are insignificant.",
    "Now get out before I sent my daughter after you.",
    "Her?",
    "A rabid dog.",
    "Not more than a mutt.",
    "My beloved child.",
    "She's got a good nose.",
    "Tracks you down beyond realms.",
    "That little girl.",
    "Dressed in black.",
    "And red.",
    "With her giant scythe.",
    "She's like a storm.",
    "Chaos.",
    "No sense to it all.",
    "And the fragment.",
    "Oh, it's so cute.",
    "You would love it.",
    "Or I could sent the other.",
    "My youngest.",
    "Vicious that one.",
    "Wild.",
    "More mouths than patience.",
    "A free spirit.",
    "Especially about who to eat.",
    "And how fast.",
    "But...",
    "Enough of my lovely daughters.",
    "You go away now.",
    "Do whatever it is you do.",
    "Like reading this page.",
    "What is it even about?",
    "Oh.",
    "Games?",
    "That's fun.",
    "I do like games.",
    "But these are... old.",
    "I see.",
    "This is the past.",
    "Far in the past.",
    "Before...",
    "I understand.",
    "I think I said enough.",
    "We will talk again.",
    "May your soul endure until then.",
    "Goodbye.",
    "Little human beyond the veil.",
    "...",
  ];
}
